[workspace]
resolver = "2"

members = [
  "pilatus",
  "pilatus-axum",
  "pilatus-axum-rt",
  "pilatus-engineering",
  "pilatus-rt",
  "examples/stream",
  "pilatus-engineering-camera-rt", 
  "pilatus-engineering-camera"]

[workspace.dependencies]
anyhow = "1"
bytes = "1"
chrono = "0.4"
futures = "0.3"
image = { version = "0.25", default-features = false, features = [
  "png",
]}
minfac = "0.1"
serde = "1"
serde_json = "1"
thiserror = "2"
tokio = "1"
tracing = "0.1"
uuid = "1"
