[package]
name = "stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pilatus = { path = "../../pilatus" }
pilatus-rt = { path ="../../pilatus-rt" }
pilatus-axum-rt = {path = "../../pilatus-axum-rt"}
pilatus-axum = {path = "../../pilatus-axum"}
minfac = "0.0.1"
serde = "1"
tokio = {version="1", features = ["sync"]}
sealedstruct = {git = "https://github.com/mineichen/sealedstruct.git", branch = "main"}
futures = "0.3"
anyhow = "1"
coinbase-pro-rs = "0.8.1"
serde_json = "1"
tracing = "0.1"

[dev-dependencies]
tokio = {version="1", features = ["sync", "macros"]}