[package]
edition = "2021"
name = "pilatus-engineering"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
approx = "0.5"
futures = { workspace = true }
image = { workspace = true, optional = true }
minfac = { workspace = true, optional = true }
nalgebra = { version = "0.33", optional = true }
pilatus = { path = "../pilatus", features = ["subscribe"] }
pilatus-rt = { path = "../pilatus-rt", optional = true }                       # Must remain an internal dependency
resvg = { version = "0.43.0", optional = true }
seahash = "4.1"
sealedstruct = { git = "https://github.com/mineichen/sealedstruct.git", branch = "main", features = [
  "serde",
] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"], optional = true }
tokio-stream = { version = "0.1", features = ["fs", "sync"], optional = true }
tracing = { workspace = true }

[dev-dependencies]
nalgebra = "0.33"
serde_json = { workspace = true }
pilatus-rt = { path = "../pilatus-rt", features = ["unstable"] }


[features]
default = ["image-algorithm"]
tokio = ["dep:tokio", "tokio-stream"]
image-algorithm = ["image", "minfac", "resvg"]
unstable = ["pilatus-rt/unstable"]
